### ISSUE TITLE
Fix: If I click outside the unlock password modal, it incorrectly makes the modal go away

### ISSUE THREAD

**Issue by atrefonas** [algodex/trading-bot#118]
# ℹ Overview

![image](https://user-images.githubusercontent.com/72869083/201150396-b7654820-d6c5-4ee5-8c29-e6c94288ecc4.png)

**Comment by treasurechic** [comment]
Yes, the modal can close if a user clicks outside the modal, you still won’t be able to trade without entering the password as I will bring it up again when you click the start button if you haven’t entered it the first time.

**Comment by hasyminh** [comment]
I have tried that. After I clicked outside the modal, it went away. The wallet still looked connected but when I started the bot, it wasn't successfull. We should have an alert message asking users to refresh then type the password again to proceed.

**Comment by treasurechic** [comment]
@hasyminh When you click start, it brings up the modal again for you to enter your password.

**Comment by atrefonas** [comment]
It’s unclear if the wallet is unlocked or locked though until you press the
start button. I think the UI should tell you somewhere. Maybe Steph can
help with the design update if it makes sense.
