### ISSUE TITLE
Fix: Mainnet environment instantiation doesn't work running locally. 

### ISSUE THREAD

**Issue by ericsharma** [algodex/trading-bot#168]
# ℹ Overview
Checking `globalThis.location.protocol` might work when the app is built, but when running locally `AlgodexApi()` is initiatied with a dexd uri of `localhost:3000`

**Comment by atrefonas** [comment]
It shouldn't use the window location when running locally. 

It should use https://app.algodex.com/api/v2

**Comment by atrefonas** [comment]
Also CORS isn't an issue locally

**Comment by ericsharma** [comment]
Just requested you for review in a simple fix

**Comment by atrefonas** [comment]
Is this fixed? @ericsharma @treasurechic

**Comment by ericsharma** [comment]
@atrefonas Closing now, it was related to #169 which I closed without merging after discussing with @treasurechic.
