### ISSUE TITLE
Feature: Add link to Github and all socials on bottom of page

### ISSUE THREAD

**Issue by atrefonas** [algodex/trading-bot#184]
# ℹ Overview

Github, Telegram, Discord, Reddit, Twitter

**Comment by stephclarkga** [comment]
I think the icons might look better with a small footer down there where we can also put a © Algonaut Capital label and maybe disclosures (if there's anything we want to put there) or any docks. Should be stickied to the bottom so it doesn't scroll

https://user-images.githubusercontent.com/59464107/205137037-3c7ed649-34b7-4602-b7c4-83aacd8aa799.mov

**Comment by treasurechic** [comment]
Oh, I'm just seeing this update

**Comment by stephclarkga** [comment]
I just added it since it just seemed off to me just having the icons by themselves. We can start with just the © Algonaut Capital on the left for now and add if we need to but it needs something over there

**Comment by stephclarkga** [comment]
> This looks good but if the footer is sticky; what about when it is on mobile?....won't it be obstructive to the contents of the page🤔

Oh I thought the bot didn't really work on mobile anyway - I never designed screens with mobile in mind. For the mobile version it doesn't have to be sticky

**Comment by stephclarkga** [comment]
Also the Discord icon looks a bit blurry compared to the others - I think the one in the Figma file should be good (it should be a vector file) otherwise I can find a different one

**Comment by treasurechic** [comment]
Yea, update the icon too

**Comment by atrefonas** [comment]
@treasurechic We don't need to support mobile right now, people will only realistically use the bot on desktop. So it's ok if it doesn't look good on mobile
