### ISSUE TITLE
Feature: Available Balance should have an (i) hover saying that it's the available balance of your wallet not including your orders

### ISSUE THREAD

**Issue by atrefonas** [algodex/trading-bot#188]
# ℹ Overview

Please consult with @stephclarkga for exact message

**Comment by stephclarkga** [comment]
Maybe something like this: "Available Balance is your current balance available to place new orders. It does not include any assets currently in placed orders."

<img width="869" alt="Screen Shot 2022-11-29 at 3 27 33 PM" src="https://user-images.githubusercontent.com/59464107/204640705-4f9b968a-649f-4187-8610-854af4cb24ff.png">


We might also want to consider making another column to the chart that shows the "Balance in Orders" (something like that)
