### ISSUE TITLE
Fix: "Cancel All Orders" should indicate it is only canceling for the current asset

### ISSUE THREAD

**Issue by atrefonas** [algodex/trading-bot#189]
# ℹ Overview

Consult with @stephclarkga for designs. Maybe just have in an (i) symbol with a tooltip hover?

**Comment by stephclarkga** [comment]
I would do something like this with text below the button with the info icon: 

<img width="784" alt="Screen Shot 2022-11-29 at 12 38 19 PM" src="https://user-images.githubusercontent.com/59464107/204602120-eb4eb3aa-ea21-4909-ae42-1b9c9c82938e.png">

**Comment by atrefonas** [comment]
Looks good to me
