### ISSUE TITLE
Fix: White screen of death

### ISSUE THREAD

**Issue by scholtz** [algodex/trading-bot#227]
# ℹ Overview

When i enter password, select USDC on mainnet it throws this error and shows blank screen.

![image](https://user-images.githubusercontent.com/1223439/208063426-079f0f5c-259f-41c2-a1d6-4b343bde4bce.png)

There does not seems to be any failed request.

### 📝 Related Issues

No

**Comment by treasurechic** [comment]
Hello @scholtz , can you make a video of this instance and share ?
